# Generated by Django 4.1.1 on 2022-09-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('desig', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
